# For more configuration details:
# https://docs.codecov.io/docs/codecov-yaml
# Validation check:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

coverage:
  status:
    patch: false
    project:
      default:
        threshold: 0.1%

  range: 70..90
  round: down
  precision: 2

ignore:
  - docs/.*
  - vrp-core/examples/.*

comment:
  layout: diff, files