[book]
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
description = "This book describes a Vehicle Routing Problem solver."
language = "en"
multilingual = false
src = "src"
title = "A Vehicle Routing Problem Solver Documentation"

# cargo install mdbook-puml
[preprocessor.puml]

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/reinterpretcat/vrp/"
additional-css = [
    "resources/leaflet.css"
]
additional-js = [
    "resources/leaflet.js",
    "resources/map.js"
]

[output.html.fold]
enable = true
level = 1
