name: Publish wheels to GitHub

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.11]  # Specify your required Python versions here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust
        if: runner.os == 'ubuntu'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install maturin
        run: pip install maturin==0.14

      - name: Build wheel
        run: maturin build --release --features "py_bindings"

      - name: Upload Python Package to GitHub Packages
        run: |
          python -m pip install twine
          python -m twine upload --repository-url https://ghcr.io/v2/OWNER/REPO dist/*.whl
        env:
          TWINE_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
